### ISSUE TITLE
no aura authorities

### ISSUE THREAD

**Issue by tansaku** [substrate-developer-hub/cumulus-workshop#49]
apologies for the noob question, but I'm working through the tutorial and trying to modify the chainspec.  I've just backed up and re-run through these tutorials:

1) https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain
2) https://substrate.dev/docs/en/tutorials/start-a-private-network

to refresh on chain specs, and I'm on https://substrate.dev/cumulus-workshop/#/en/1-prep/2-chain-spec?id=adjust-the-chain-spec

I notice we have:

```
        "palletGrandpa": {
          "authorities": []
        },
```

ready to be filled out, but unlike in the previous tutorials, there is no aura authorities - is that just a version difference?   In the "start a private network" tutorial we had:

```
      "palletAura": {
        "authorities": [
          "5FfBQ3kwXrbdyoqLPvcXRp7ikWydXawpNs2Ceu3WwFdhZ8W4",
          "5EhrCtDaQRYjVbLi7BafbGpFqcMhjZJdu8eW8gy6VRXh6HDp"
        ]
      },
      "palletGrandpa": {
        "authorities": [
          [
            "5G9NWJ5P9uk7am24yCKeLZJqXWW6hjuMyRJDmw4ofqxG8Js2",
            1
          ],
          [
            "5CRZoFgJs4zLzCCAGoCUUs2MRmuD5BKAh17pWtb62LMoCi9h",
            1
          ]
        ]
      },
```

I'd be very grateful if anyone can explain the reason.  maybe palletAura just not necessary for this particular tutorial?

**Comment by JoshOrndorff** [comment]
Thanks for referring to the tutorials before asking your question. That makes int not a noob question :)

In both of those tutorials, you are using the Substrate node template which uses Aura/Grandpa consensus and no session rotation.

In this cumulus workshop, you are modifying the spec for a Polkadot node. Polkadot is different than the node template in some ways that you are noticing. Polkadot uses Babe/Grandpa consensus and _does_ use session rotation.

The easy-to-understand difference is the Babe vs Arua. You've correctly observed that there is no aura section in the Polkdaot spec. Look for the babe section instead.

The harder-to-understand part is about session rotation. In the node template the authorities will use the same keys forever. This is nice and simple and a good way to start learning. But it is not great for production because the authority would have no recourse if their key got compromised, and key rotation is generally a good cryptographic best-practice. To solve this Polkdot uses the Sessions pallet. So instead of configuring your authority keys directly in the Babe and Grandpa pallets, you instead configure them in the Sessions pallet. Find that section in the config, and use the tutorial to help you understand how to update the spec.

For general reading on Polkadot's session keys, check out https://wiki.polkadot.network/docs/en/learn-keys#session-keys

**Comment by tansaku** [comment]
wow! thanks @JoshOrndorff for the detailed explanation - very much appreciated
